### ISSUE TITLE
Using .distort() with SRT string fails

### ISSUE THREAD

**Issue by pduersteler** [janko/image_processing#68]
I am trying to use the following imagemagick command through image_processing:

```
magick convert input.jpg \
  -set option:distort:viewport 295x195 \
  -distort SRT "1281,422 0.24 0 147,97" \
  output.jpg
```

I could not get it working through the rails variants in rails 6, which as far as I understood, use image_processing under the hood. So I tried it directly in image_processing first to see if and where things go south. What I tried was:

```
ImageProcessing::MiniMagick.source('input.jpg')
  .set('option:distort:viewport 295x195')
  .distort('SRT "1281,422 0.24 0 147,97"')
  .call
```

Which results in:

```
MiniMagick::Error: `convert input.jpg -auto-orient -set option:distort:viewport 295x195 
-distort SRT '1281,422 0.24 0 147,97' /var/folders/qt/whql0l6s29l6dcw_rwc4ds8r0000gp/T/image_processing20200403-29104-14c51ws.jpg`
failed with error:

convert: unable to open image 'SRT '1281,422 0.24 0 147,97'': No such file or directory @ error/blob.c/OpenBlob/3496.
convert: no decode delegate for this image format `24 0 147,97'' @ error/constitute.c/ReadImage/562.

from .../.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mini_magick-4.9.5/lib/mini_magick/shell.rb:17:in `run'
from .../.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mini_magick-4.9.5/lib/mini_magick/tool.rb:90:in `call'
from .../.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/image_processing-1.9.3/lib/image_processing/mini_magick.rb:55:in `save_image'
```

So I tried to check if I can reproduce the error in mini_magick with:

```
image = MiniMagick::Image.open('input.jpg')
  .set 'option:distort:viewport 295x195'
  .distort "SRT '1281.6433333333332,422.52808988764053 0.24 0 147.5,97.5'"
  .resize '295x195'
  .write 'result.jpg'
```

The command here does not fail, however the resulting output is different than the one coming from the command line, but this may be a different issue.

I'm not sure if I am doing something wrong or if this is really a bug, and if so, if this is the right place for this, but I thought I'd give it a try.

**Comment by pduersteler** [comment]
I could solve this, apparently it makes a big difference if you pass strings with spaces as one param or as multiple params.

The correct way to do is seems to be:

    .set('option:distort:viewport', '295x195')
    .distort('SRT', '1281.6433333333332,422.52808988764053 0.24 0 147.5,97.5')
