### ISSUE TITLE
unrecognized option `-resize-to-limit' 

### ISSUE THREAD

**Issue by shqear93** [janko/image_processing#90]
I'm not sure what is the issue and why, I'm not sure if this the right repo to report!
I use rails (6.0.4) with active storage activestorage (6.0.4) and it's failing in rails admin (rails_admin (2.1.1)) despite I don't use any scustom functionalities like `variant` method or even `resize-to-limit` 

Error:
```
MiniMagick::Error: `mogrify -resize-to-limit [100, 100] /tmp/ActiveStorage-2788-20210817-21988-qbyshn.jpeg` failed with error:
mogrify: unrecognized option `-resize-to-limit' @ error/mogrify.c/MogrifyImageCommand/5525.

  from mini_magick (4.11.0) lib/mini_magick/shell.rb:17:in `run'
  from mini_magick (4.11.0) lib/mini_magick/tool.rb:92:in `call'
  from mini_magick (4.11.0) lib/mini_magick/tool.rb:38:in `new'
  from mini_magick (4.11.0) lib/mini_magick/image.rb:594:in `mogrify'
  from activestorage (6.0.4) lib/active_storage/transformers/mini_magick_transformer.rb:13:in `block in process'
  from activestorage (6.0.4) lib/active_storage/transformers/mini_magick_transformer.rb:12:in `each'
  from activestorage (6.0.4) lib/active_storage/transformers/mini_magick_transformer.rb:12:in `process'
  from activestorage (6.0.4) lib/active_storage/transformers/transformer.rb:25:in `transform'
  from activestorage (6.0.4) app/models/active_storage/variation.rb:52:in `block in transform'
  from activesupport (6.0.4) lib/active_support/notifications.rb:180:in `block in instrument'
  from activesupport (6.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.0.4) lib/active_support/notifications.rb:180:in `instrument'
  from activestorage (6.0.4) app/models/active_storage/variation.rb:51:in `transform'
  from activestorage (6.0.4) app/models/active_storage/variant.rb:105:in `transform'
  from activestorage (6.0.4) app/models/active_storage/variant.rb:100:in `block in process'
  from activestorage (6.0.4) lib/active_storage/downloader.rb:15:in `block in open'
  from activestorage (6.0.4) lib/active_storage/downloader.rb:24:in `open_tempfile'
  from activestorage (6.0.4) lib/active_storage/downloader.rb:12:in `open'
  from activestorage (6.0.4) lib/active_storage/service.rb:87:in `open'
  from activestorage (6.0.4) app/models/active_storage/blob.rb:217:in `open'
  from activestorage (6.0.4) app/models/active_storage/variant.rb:99:in `process'
  from activestorage (6.0.4) app/models/active_storage/variant.rb:67:in `processed'
  from activestorage (6.0.4) app/controllers/active_storage/representations_controller.rb:12:in `show'
  from actionpack (6.0.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from actionpack (6.0.4) lib/abstract_controller/base.rb:195:in `process_action'
  from actionpack (6.0.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
  from actionpack (6.0.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  from activesupport (6.0.4) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
  from sentry-raven (3.1.2) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from activesupport (6.0.4) lib/active_support/callbacks.rb:121:in `instance_exec'
  from activesupport (6.0.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from activesupport (6.0.4) lib/active_support/callbacks.rb:139:in `run_callbacks'
  from actionpack (6.0.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
  from actionpack (6.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
  from actionpack (6.0.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from activesupport (6.0.4) lib/active_support/notifications.rb:180:in `block in instrument'
  from activesupport (6.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.0.4) lib/active_support/notifications.rb:180:in `instrument'
  from actionpack (6.0.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  from actionpack (6.0.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  from activerecord (6.0.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  from actionpack (6.0.4) lib/abstract_controller/base.rb:136:in `process'
  from actionview (6.0.4) lib/action_view/rendering.rb:39:in `process'
  from actionpack (6.0.4) lib/action_controller/metal.rb:190:in `dispatch'
  from actionpack (6.0.4) lib/action_controller/metal.rb:254:in `dispatch'
  from actionpack (6.0.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  from actionpack (6.0.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  from actionpack (6.0.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack-pjax (1.1.0) lib/rack/pjax.rb:12:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack-tracker (1.12.1) lib/rack/tracker.rb:45:in `_call'
  from rack-tracker (1.12.1) lib/rack/tracker.rb:41:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from remotipart (1.4.4) lib/remotipart/middleware.rb:32:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
  from warden (1.2.9) lib/warden/manager.rb:34:in `catch'
  from warden (1.2.9) lib/warden/manager.rb:34:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/etag.rb:27:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/head.rb:12:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/cookies.rb:654:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from activesupport (6.0.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
  from actionpack (6.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from railties (6.0.4) lib/rails/rack/logger.rb:37:in `call_app'
  from railties (6.0.4) lib/rails/rack/logger.rb:26:in `block in call'
  from activesupport (6.0.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
  from activesupport (6.0.4) lib/active_support/tagged_logging.rb:28:in `tagged'
  from activesupport (6.0.4) lib/active_support/tagged_logging.rb:80:in `tagged'
  from railties (6.0.4) lib/rails/rack/logger.rb:26:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/method_override.rb:24:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from activesupport (6.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from actionpack (6.0.4) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from sentry-raven (3.1.2) lib/raven/integrations/rack.rb:51:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from railties (6.0.4) lib/rails/engine.rb:527:in `call'
  from newrelic_rpm (7.1.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
  from passenger (6.0.7) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
  from passenger (6.0.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  from passenger (6.0.7) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  from passenger (6.0.7) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  from passenger (6.0.7) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```

**Comment by janko** [comment]
I would need code that generates this variant in order to be able to determine where is the failure coming from. The most likely reason is that MiniMagick transformer has been configured instead of ImageProcessing transformer. The former is deprecated as far as I remember, so you should switch to the latter.

**Comment by shqear93** [comment]
@janko this is created by rails admin, still not able to reproduce seems like happening randomly but in a crazy way, I'm getting thousands of this error even thu it's not causing a bug on the website

**Comment by janko** [comment]
Since it doesn't seem to be an issue with this gem, I'm closing this one for now.
